### ISSUE TITLE
Simple dynamic query fails

### ISSUE THREAD

**Issue by llewelynrex** [mbarbac/Kerosene.ORM#2]
Hi there,

I've been trying out version 7.3 of Kerosene on Visual Studio 2015 RC on Windows 10 Build 10130. I keep getting an exception : "An unhandled exception of type 'System.ArgumentException' occurred in Kerosene.Tools.dll Additional information: Not enough non-dynamic arguments in '[]'."

The exception occurs when running the following piece of code: "var data = dataLink.From( o => o.Production.Product );". I'm simply using the AdventureWorks database to try out Kerosene.ORM.

Is this simply an issue with my environment or am I doing something stupid? I've tried replacing the dataLink.From with a dataLink.Raw method and adding a raw string query. That worked without any problems.

Brilliant piece of code though! I've tried it out a while back and I was thoroughly impressed!

PS: I've had a look at the articles you have on codeplex. They appear to be a little out of date? Some methods and Factories seem to have been deprecated. Will there be an update at some point?

**Comment by mbarbac** [comment]
Hi, and thanks for your nice words.

First thing first: 7.3 is the latest version published, but I'm currently working in the integration of Kerosene.ORM with the new Aspnet Identity system. Looks like it has some weird behaviors in terms of libraries' resolution, among others, and I'm trying to polish it before publishing... which possibly worth another version number (buf!). And, yes, indeed, articles in codeplex are slightly out of date... not enough hours per day to do everything at once.

Now, answering your question: this exception occurs when you're trying to parse a dynamic lambda expression, or delegate, that has both dynamic and non-dynamic arguments and the number of the non-dynamic ones is not enough to "execute" the delegate. In your case the 'o.Production.Product' piece shall resolve into a table name, a string, which seems not to be the case.

If you have handy a string containing the name of your table (say in a string variable named 'myname') try: 'dataLink.From(x => myname)'. Or if your table is named 'Products' you can try 'dataLink.From(x => x.Products)'... the reason is that the 'From()' method expects an argument that resolves into a table name.

Let me know if this has solved your issue. Cheers, Moises.

**Comment by llewelynrex** [comment]
Hi,

thanks for the quick reply. I can definitely identify with being too 
swamped for documentation!

I've attempted using a string and different variations of table name and 
schema name. Running the three queries below ought to provide the same 
result, but the second and third ones keep failing. They just refuse to 
resolve properly or they resolve and maybe there is something wrong with 
my database or environment.

```
         var test = dataLink.Raw( "select * from Production.Product" 
```

); //Works

```
         var data1 = dataLink.From( o => "Production.Product" ); 
```

//Exception

```
         var data2 = dataLink.From( o => o.Production.Product ); 
```

//Exception

I don't want us to chase our tails here. I am on a Beta environment 
anyway using Windows 10 Insider Preview Build 10162 and Visual Studio 
2015 Community RC with a Microsoft SQL Server Express 2014 database.

If I get to it, I can try testing at work tomorrow. I'm on Windows 7 
Professional there and using Visual Studio 2013 Professional Update 4. I 
have a SQL Server 2008 database I can connect to there.

Cheers,
Llewelyn Rex

Am 06/07/2015 um 23:40 schrieb Moises Barba Cebeira:

**Comment by llewelynrex** [comment]
Hi there,
I've just tested Kerosene 7.4 on my machine at work and as I suspected, it works. It's probably something to do with my home environment. It works fine here. Now I get to play with it. :)

CheersLlewelyn Rex
Subject: Re: [Kerosene.ORM] Simple dynamic query fails (#2)
To: reply@reply.github.com
From: llewelyn.rex@outlook.com
Date: Tue, 7 Jul 2015 23:48:41 +0200

```
Hi,



thanks for the quick reply. I can definitely identify with being too
swamped for documentation! 



I've attempted using a string and different variations of table name
and schema name. Running the three queries below ought to provide
the same result, but the second and third ones keep failing. They
just refuse to resolve properly or they resolve and maybe there is
something wrong with my database or environment.



            var test = dataLink.Raw( "select * from
Production.Product" ); //Works



            var data1 = dataLink.From( o => "Production.Product"
); //Exception



            var data2 = dataLink.From( o => o.Production.Product
); //Exception



I don't want us to chase our tails here. I am on a Beta environment
anyway using Windows 10 Insider Preview Build 10162 and Visual
Studio 2015 Community RC with a Microsoft SQL Server Express 2014
database.



If I get to it, I can try testing at work tomorrow. I'm on Windows 7
Professional there and using Visual Studio 2013 Professional Update
4. I have a SQL Server 2008 database I can connect to there.



Cheers,

Llewelyn Rex



Am 06/07/2015 um 23:40 schrieb Moises
  Barba Cebeira:



  Hi, and thanks for your nice words.

  First thing first: 7.3 is the latest version published, but I'm
    currently working in the integration of Kerosene.ORM with the
    new Aspnet Identity system. Looks like it has some weird
    behaviors in terms of libraries' resolution, among others, and
    I'm trying to polish it before publishing... which possibly
    worth another version number (buf!). And, yes, indeed, articles
    in codeplex are slightly out of date... not enough hours per day
    to do everything at once.

  Now, answering your question: this exception occurs when you're
    trying to parse a dynamic lambda expression, or delegate, that
    has both dynamic and non-dynamic arguments and the number of the
    non-dynamic ones is not enough to "execute" the delegate. In
    your case the 'o.Production.Product' piece shall resolve into a
    table name, a string, which seems not to be the case.

  If you have handy a string containing the name of your table
    (say in a string variable named 'myname') try: 'dataLink.From(x
    => myname)'. Or if your table is named 'Products' you can try
    'dataLink.From(x => x.Products)'... the reason is that the
    'From()' method expects an argument that resolves into a table
    name.

  Let me know if this has solved your issue. Cheers, Moises.

  —

    Reply to this email directly or view
      it on GitHub.
```

**Comment by mbarbac** [comment]
Nice - I have also tested Kerosene in Windows 8, 8.1 and Windows Server 2012 and 2014 without any problems, and using SQL Server 2008, 2012, and 2014.

Enjoy!

**Comment by llewelynrex** [comment]
Hi again. I know you've closed this issue, but it would seem that it's not resolved. I suspect it's related to Visual Studio 2015 or perhaps Roslyn. Let me elaborate:

I've yesterday installed the RTM version of Visual Studio 2015 Community on this machine. I'm also still running Visual Studio 2013 Community in parallel. The error message seems to only occur when I compile using Visual Studio 2015. When I run the same code using the exact same version of Kerosene on Visual Studio 2013 on the same machine, it works fine.

In both VS versions, I created the project using .NET 4.6 and I'm using the AdventureWorks SQL database on SQL Server 2014 Express.

Perhaps I could send you both of my solutions?

Llewelyn

**Comment by mbarbac** [comment]
Hi, definitely the issue has to be reopened again.

Unfortunately I have not an environment where I can test your scenario (VS 2015, .NET 4.6). Because business reasons I will not migrate until, at least, very late this year :(

So... what if you just create a console Project referencing Kerosene.ORM and just execute the offending code? If you debug step-by-step so referencing the source code instead of the NuGet package I may understand a bit more about this issue. BTW, download the latest versión if you may.

The "Not enough non-dynamic arguments" message only appears in the DynamicParser.Parse() method, When entering into it I would like firstly to know it the 'concretes' array carries any argument.

Secondly because in the ORM the signature is always Func<dynamic, object> the 'pars' array has to be populated with just one argument, the dynamic one of the lambda (the delegate). The 'isDynamic' bool has then to be true.

What is weird is that the message ends with '[]' which means that the 'concretes' array is empty... so either the GetParameters() method does not populate the 'pars' array, or the GetCustomAttributes() one is not identifying those marked with 'DynamicAttribute' attribute. Either case quite weird.

Let me know how it goes.
Cheers, Moises

**Comment by llewelynrex** [comment]
Okay, so I've had a look at the `DynamicParser.Parse(Delegate lambda,params object[] concretes)` method. Very strange. The difference comes in with the following statement:

``` C#
bool isDynamic = par.GetCustomAttributes(typeof(DynamicAttribute), true).Length != 0 ? true : false;
```

In Visual Studio 2013 the statement evaluates to true, but in Visual Studio 2015 the statement evaluates to false. That's why the exception follows.

**Comment by mbarbac** [comment]
Fantastic (sarcasm intended).

Would it be posible for your to let me know what are the actual attributes applied to the parameter 'par'? Let's see first if the 'DynamicAttribute' is applied, because if not... well I would need to investigate another way to figure out whether a parameter of a lambda is a dynamic one or not.

BTW, thanks a lot for having surfaced this issue and for your support!

**Comment by mbarbac** [comment]
Actually... would it be posible to you to replace that line with the following code?;

``` C#
bool isDynamic = false;
foreach (var attr in par.CustomAttributes) {
    if (attr.AttributeType == typeof(DynamicAttribute)) {
        isDynamic = true;
        break;
    }
}
```

It is less elegant that the one-liner version before... but it Works in my box and if it does so in yours we may have fixed the issue... :-)

**Comment by llewelynrex** [comment]
You're very welcome for the help.

Okay, I've tried your addition, but still no joy. The problem is that `par` doesn't have any CustomAttributes. The property is empty.
![image](https://cloud.githubusercontent.com/assets/9720471/8835675/351b596e-30bc-11e5-95da-5c1b8adffca3.png)

**Comment by mbarbac** [comment]
Ok, so I'll set up a machine with VS2015 and investigate the issue further.
Meanwhile, we just need to find a way to identity if an object is declared as a dynamic one or not... if you figure out a way then the issue will be done

**Comment by mbarbac** [comment]
Hi again, following code does the job:

``` C#
bool isDynamic = false;

var attrs = par.GetCustomAttributes(typeof(DynamicAttribute), true);
isDynamic = attrs.Length != 0;

if (!isDynamic)
{
    var attr = par.ParameterType.CustomAttributes.FirstOrDefault(x => x.AttributeType == typeof(ClassInterfaceAttribute));
    if (attr != null)
    {
        var arg = attr.ConstructorArguments.FirstOrDefault(x => x.ArgumentType == typeof(ClassInterfaceType));
        if (arg != null)
        {
            var cit = (ClassInterfaceType)arg.Value;
            isDynamic = cit == ClassInterfaceType.AutoDispatch || cit == ClassInterfaceType.AutoDual;
        }
    }
}
```

Now, I acknowledge that it is just a hack, not quite a robust one, as nothing impedes a parameter object to be decorated with the ClassInterfaceAttribute... but at least, when used with the ORM parsing mechanism, as far as the signature used for lambdas is always a `Func<dynamic, objec>` one, then this should not be a problem.

Cheers, Moises

**Comment by llewelynrex** [comment]
Hi again,

I've just tried out the new piece of code and that did the trick. I also tried running with strings as parameters and that worked as well. I also added a `Select` and `OrderBy` to the code and that seemed to function too. Below is what I've tested:

``` C#
var query = _dataLink.From(x => x.Production.Product).Select(x => x.ProductID, x => x.Name).OrderBy(x => x.ProductID);
```

Would you say this is a bug in Visual Studio 2015? Should this issue perhaps be logged with Microsoft? It's a bit weird that the two environments react differently to the same piece of code.

**Comment by mbarbac** [comment]
Glad to see it Works in your installation too :-)!

And, indeed, I would say so - I have just filed the bug (ID: 1580562)... let's see if someone is paying attention!
